### PR TITLE
Global refactoring

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Package out of date*
- *There're some rm -rf somewhere*

## Solution
- *Global refactoring*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : JimboJoe
- [x] **Code review** : frju365 
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : frju365
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by frju365** [comment]
Perhaps merge #37 first ?

**Comment by frju365** [comment]
in, fact, no... nvm.

**Review by frju365 — APPROVED** [review]

**Review by JimboJoe — APPROVED** [review]
LGTM and tested (rather quickly) upgrade from previous version

**Comment by JimboJoe** [comment]
Will be merged in testing in 3 days 👍

**Pull request merged**
