### PR TITLE
Package upgrade

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Global upgrade of the package.*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/rainloop_ynh%20package_upgrade%20(Official)/) 
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Sorry @yalh76 that I rushed into the testing branch, forgetting your work...
So, I think this PR should wait for https://github.com/YunoHost-Apps/rainloop_ynh/pull/52 to be merged. And then work on the diff and merge this one.

**Comment by yalh76** [comment]
> 
> 
> Sorry @yalh76 that I rushed into the testing branch, forgetting your work...
> So, I think this PR should wait for #52 to be merged. And then work on the diff and merge this one.

No pb, I think that the diff won't be too huge, I used the global_upgrade branch of example_ynh... 14 days ago

**Review by JimboJoe — DISMISSED** [review]
LGTM :+1:

**Review by kay0u — DISMISSED** [review]
LGTM

**Comment by alexAubin** [comment]
smol bump because this (+#50) look like important work :s

**Review by yalh76 — APPROVED** [review]
LGTM

**Comment by alexAubin** [comment]
Bump ... would be nice to move forward with this and / or #50 :s

**Review by kay0u — APPROVED** [review]
LGTM & code review

**Comment by kay0u** [comment]
Can be merged in 3 days

**Comment by kay0u** [comment]
I merge it, since the only commit after our review is to fix a merge on check_process

**Pull request merged**
