### PR TITLE
Temporary fix for getopts

### LINKED ISSUE #58: Installation Fails during 'Configuring Rainloop' stage
Good day,
I am not very good at being able to extract log files (working on it) but I wanted to send this right away because there are others who are confirming this bug.

During installation process, in the 'configuring rainloop' stage, it gets stuck and does not proceed to successful installation.  

Another user in the group confirmed this.  I will try to reply to this with my error logs if I can figure out how to get them out of the server...

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Getopts fails to parse a value if it's start by -. It's misread as another option in the argument list.*

## Solution
- *Fix #58*
- *This is a temporary fix on rainloop part, see https://github.com/YunoHost/yunohost/pull/752 for a general fix.*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/rainloop_ynh%20PR59/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Review by kay0u — APPROVED** [review]
LGTM & code review

**Review by JimboJoe — APPROVED** [review]
LGTM :+1:

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Comment by maniackcrudelis** [comment]
Should we start a testing release with a 7 days waiting time for this PR ?
This is not a huge fix, but it will solve install issues for American users.

**Comment by kay0u** [comment]
I don't think it's necessary, let's merge it 3 days after 2 LGTM...

**Pull request merged**
